# ᕦ(ツ)ᕤ
# test/test.py
# generated by zeta.py
                
import numpy as np
        
def run():
    a_0_x = np.float32(1)
    b_1_x = np.float32(4)
    v_3_x = a_0_x - b_1_x
    n_9 = v_3_x * v_3_x
    a_0_y = np.float32(2)
    b_1_y = np.float32(5)
    v_3_y = a_0_y - b_1_y
    n_10 = v_3_y * v_3_y
    n_8 = n_9 + n_10
    a_0_z = np.float32(3)
    b_1_z = np.float32(6)
    v_3_z = a_0_z - b_1_z
    n_11 = v_3_z * v_3_z
    n_7 = n_8 + n_11
    d_2 = np.sqrt(n_7)
    print(f"a_0.x = {a_0_x}")
    print(f"b_1.x = {b_1_x}")
    print(f"v_3.x = {v_3_x}")
    print(f"n_9 = {n_9}")
    print(f"a_0.y = {a_0_y}")
    print(f"b_1.y = {b_1_y}")
    print(f"v_3.y = {v_3_y}")
    print(f"n_10 = {n_10}")
    print(f"n_8 = {n_8}")
    print(f"a_0.z = {a_0_z}")
    print(f"b_1.z = {b_1_z}")
    print(f"v_3.z = {v_3_z}")
    print(f"n_11 = {n_11}")
    print(f"n_7 = {n_7}")
    print(f"d_2 = {d_2}")

if __name__ == "__main__":
    run()